### ISSUE TITLE
hocr-extract-images doesn't see image

### ISSUE THREAD

**Issue by bicolino34** [ocropus/hocr-tools#185]
I had a one .jpg image and created hocr file for it with the program gImageReader. They have identical names and are located in the same directory.
I tried to run in terminal to see how the script works: `hocr-extract-images ./20240128_105503.html`
It produces the error: `not found: './20240128_105503.jpg'` even though the image file is in the very same directory with this name that is shown as not found.
Specifying image directory with -b doesn't help. I also tried converting image to .png

**Comment by FriedrichFroebel** [comment]
How does your tag defining the page with its image look like?

**Comment by FriedrichFroebel** [comment]
This is related to https://github.com/ocropus/hocr-tools/blob/2867727ae986dd1e1727d98300da053caaffdb9b/hocr-extract-images#L28 where single quotation marks are expected in the outer level and only double quotation marks as nested values. Using

```python3
            args = args.strip('"\'')
```

there instead seems to fix it.

**Comment by bicolino34** [comment]
Thank you! This has solved the issue
